### ISSUE TITLE
Suit upgrade-ability

### ISSUE THREAD

**Issue by Nightside101010** [Sigma88/Sigma-Replacements#23]
FEATURE REQUEST:
Make Kerbal{Requirements} for Suits and Heads aware of career mode upgrades.
- [x] technode unlock
- [x] Building level
- [x] Kerbal level
- [x] parts

Would it be possible to have a suit & head requirement that could change during gameplay to "unlock" new suits when techs are unlocked (or buildings upgraded) in career/science mode?
Something like:
`Kerbal
{
    Requirements
    {
        experienceLevel= 3
    }
}`

In case my kerbals want to get a new face tattoo each time they get some more experience.

**Comment by Sigma88** [comment]
kerbal level is already available using `minLevel` and `maxLevel`

the others should be possible, I'll try to add them as soon as I have some time

👍

**Comment by Nightside101010** [comment]
Thanks, I will try to make something with the levels tonight.

**Comment by Sigma88** [comment]
I took the liberty to update your comment so that it shows the list of features that are implemented and those that are still missing

feel free to add more if you want

**Comment by Nightside101010** [comment]
From: [https://forum.kerbalspaceprogram.com/index.php?/topic/147576-modders-notes-for-ksp-12/]
PartModule Upgrades:

PartModules now support upgrades. Upgrades are unlocked via the Tech Tree in career mode and Use the entryCost field.

PartModule PartStatsUpgradeModule is used to upgrade PART node stats.

PartModule.showUpgradesInModuleInfo is a new KSPField bool. If true Upgrade information will be compiled into the PartInfo and shown where applicable.

An UPGRADES node can be added to a PartModule Node to upgrade stats within a PartModule. Multiple UPGRADE nodes are specified within the UPGRADES node to upgrade stats.

A PARTUPGRADE node is added which is us

ed for displaying the Icons and tooltips in the TechTree.

The PartUpgradeManager ScenarioModule handles the Upgrading. Mods can Interface to this to modify the stock upgrade behaviour and extend.
 

UPGRADE nodes can now have ExclusiveWith__ = [some string]

This means you can chain upgrades. Only the last found upgrade of the given string is applied.

PartStatsUpgradeModule can now specify mass = [amount] and/or cost = [amount] for an UPGRADE node to specify specific mass or cost to an upgrade.

You can also alternatively specify massAdd = [amount] and/or costAdd = [amount] for an UPGRADE node to additively add mass or cost to the previous values.

An Example is easier, this MM file will update the LVT45 maxThrust on the ModuleEngines and maxTemp on the part at GeneralRocketry and AdvRocketry.
Note the "IsAdditiveUpgrade__" field. This field tells the PartModule Load to add the UPGRADE nodes additive. If it is false the nodes will overwrite each other this is only applicable to the PartStatsUpgradeModule.
 

 

@PART[liquidEngine2]
{
	@MODULE[ModuleEngines]
	{		
		showUpgradesInModuleInfo = true
		UPGRADES
		{
			UPGRADE
			{
				name__ = LVT45-GenRocketry-Thrust
				techRequired__ = generalRocketry							
				maxThrust = 400
			}
			UPGRADE
			{
				name__ = LVT45-AdvRocketry-Thrust
				techRequired__ = advRocketry 				
				maxThrust = 900
			}
		}
	}
	MODULE
    {
        name = PartStatsUpgradeModule
        showUpgradesInModuleInfo = true
		UPGRADES
        {
            UPGRADE 
            {
                name__ = LVT45-GenRocketry-Thrust
                techRequired__ = generalRocketry
				IsAdditiveUpgrade__ = True	
                PartStats
                {
					maxTemp = 2500
				}
            }
			UPGRADE 
            {
                name__ = LVT45-AdvRocketry-Thrust
                techRequired__ = advRocketry
				IsAdditiveUpgrade__ = True	
				PartStats
                {
					maxTemp = 2900
				}
            }
        }
    }	
}

PARTUPGRADE
{
	name = LVT45-GenRocketry-Thrust
	partIcon = liquidEngine2
	techRequired = generalRocketry
	entryCost = 10000
	title = LV-T45 Thrust Upgrade
	description = The LV-T45 engine now generates 400 kN of thrust and has a max temp of 2500.
}
PARTUPGRADE
{
	name = LVT45-AdvRocketry-Thrust
	partIcon = liquidEngine2
	techRequired = advRocketry
	entryCost = 50000
	title = LV-T45 Thrust Upgrade
	description = The LV-T45 engine now generates 900 kN of thrust and has a max temp of 2900.
}

**Comment by Sigma88** [comment]
so if I understand this correctly the parts are all generated as "base" and then you can upgrade the individual parts?

rather than just unlocking better parts... that might be a bit more complicated to do...

I'll see what I can do

**Comment by Sigma88** [comment]
I've added the techRequirement option

for the syntax, just add as many `techRequired = XXXX` you want inside the `Requirements` node.

all `techRequired` must be unlocked in order for the changes to be applied

the mainmanu and sandbox games will automatically match all `techRequired`

[Sigma-Replacements.techRequirements-alpha1.zip](https://github.com/Sigma88/Sigma-Replacements/files/1567541/Sigma-Replacements.techRequirements-alpha1.zip)

**Comment by Sigma88** [comment]
I've also added buildings requirements.

syntax:

```
@SigmaReplacements
{
    Kerbal
    {
        Requirements
        {
            Building
            {
                name = TrackingStationBuilding
                minLevel = 1
                maxLevel = 1
            }
        }
        Head
        {
            head = 1.13,0.85,1,1
        }
    }
}
```

this will change the color of kerbal faces when the tracking station level is 1 (the starting level is 0)

you can define as many `Building` nodes as you want, all of them need to match in order for the changes to be applied.

a `Building` gives a positive match when:

- there are no buildings of type `name`
or
- the current level of the first building of type `name` is within the `minLevel` - `maxLevel` range

if `minLevel` or `maxLevel` are not defined it means there will be no lower/upper bound for the building level.

here are the plugins:
[Sigma-Replacements.newRequirements-alpha2.zip](https://github.com/Sigma88/Sigma-Replacements/files/1568238/Sigma-Replacements.newRequirements-alpha2.zip)
@milljm you can use these plugins to test issue #24 


this feature is compatible with custom upgradeable buildings as long as you use the correct name.

the list of stock building types is:

```
AdministrationFacility
AstronautComplexFacility
FlagPoleFacility
LaunchSiteFacility
LaunchSiteFacility
MissionControlBuilding
RnDBuilding
SpacePlaneHangarBuilding
TrackingStationBuilding
VehicleAssemblyBuilding
```

**Comment by Sigma88** [comment]
I took a look at the `PARTUPGRADE` system and after bothering @JadeOfMaar for quite a while I think I have a general idea of how the system works.

As far as I can tell there is no real advantage in using the upgrade system for suits / heads.

If you know of any reason to use the upgrades let me know.

On the other hand, having the ability to check for unlocked parts would be useful, so I'm trying to implement that now.

**Comment by Nightside101010** [comment]
Nice, thanks for the new tools!
I agree regarding the upgrades.

**Comment by Sigma88** [comment]
I've added the possibility to check for parts, you just need to add `partPurchased = mk1pod` inside the `Requirements` node.

you can add as many `partPurchased` as you desire, this check will fail if it finds the part but the part is not purchased

if the part doesn't exist it will count as "purchased"


[Sigma-Replacements.newRequirements-alpha4.zip](https://github.com/Sigma88/Sigma-Replacements/files/1571277/Sigma-Replacements.newRequirements-alpha4.zip)

**Comment by Sigma88** [comment]
turns out there actually is a reason to prefere `PARTUPGRADE` over `PART`

`PART`s will always have the mass and other physical parameters defined in the tooltip, while `PARTUPGRADE`s don't:

<img src="https://user-images.githubusercontent.com/12640834/34165557-e5ebdc24-e4dc-11e7-82bc-bccd6852c912.png" width="200px">

**Comment by Sigma88** [comment]
I've added `PARTUPGRADE` checks and changed the syntax a bit. The new syntax is:

```
@SigmaReplacements
{
    Kerbal
    {
        Requirements
        {
            researchRequired = basicScience
            partPurchased = largeSolarPanel
            upgradeUnlocked = mySuperCoolUpgrade
            Building
            {
                 name = VAB
                 minLevel = 1
                 maxLevel = 2
            }
        }
    }
}
```

`researchRequired` is used to check for technology unlocks
`partPurchased` is used to check for parts
`upgradeUnlocked` is used to check for upgrades

here are the dlls if any of you cares to give them a try

[Sigma-Replacements.newRequirements-alpha5.zip](https://github.com/Sigma88/Sigma-Replacements/files/1575741/Sigma-Replacements.newRequirements-alpha5.zip)


If I don't hear anything I think I will procede to releasing these

**Comment by Sigma88** [comment]
added all features requested and more :)
