### ISSUE TITLE
pood's skybox doesn't work with 0.3.0

### ISSUE THREAD

**Issue by xjames50** [Sigma88/Sigma-Replacements#67]
Hi there. Thanks for this awesome mod.

pood's skybox doesn't work with Sigma Replacements Skybox 0.3.0.
I went back to 0.2.2 and it works fine there.

Cheers!

**Comment by Sigma88** [comment]
the syntax is changed so you need to wait for @poodmund to update his mod before going from 0.2.2 to 0.3.0

there are no issues with 0.2.2 so feel free to stick with that version for as long as you need 👍
