### ISSUE TITLE
SR: Descriptions issues in KSP 1.5.*

### ISSUE THREAD

**Issue by Poodmund** [Sigma88/Sigma-Replacements#68]
Seems to work fine except for the main part of the Descriptions tooltip not showing when you mouse over (the main part of the mod). Other than that, the Hiring screen and Editor crew lists look correct: https://i.imgur.com/duB5y38.png

**Comment by Sigma88** [comment]
it's weird because it works fine for me

**Comment by Sigma88** [comment]
```
the Descriptions tooltip not showing when you mouse over 
```

I just realized you were on a sandbox game

sandbox games don't have tooltips, that's not a bug, it's the standard stock behaviour
