### ISSUE TITLE
Missing directory  [Nyan]   make rebuild impossible

### ISSUE THREAD

**Issue by linuxgurugamer** [Sigma88/Sigma-Replacements#85]
Attempted to rebuild to fix bugs, but was thwarted by the absence of the directory  [Nyan]  as show by the errors below

Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid Resx file. Could not find file 'D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\[Nyan]\Sprites\bob'. Line 64, position 5.	SigmaReplacementsDescriptions	D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\Descriptions\Nyan.resx	64	
Error		Invalid Resx file. Could not find file 'D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\[Nyan]\SkyBox\nyanXP0'. Line 64, position 5.	SigmaReplacementsSkyBox	D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\SkyBox\Nyan.resx	64	
Error		Invalid Resx file. Could not find file 'D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\[Nyan]\nyanSuit'. Line 64, position 5.	SigmaReplacementsSuits	D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\Suits\Nyan.resx	64	
Error		Invalid Resx file. Could not find file 'D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\[Nyan]\nyanLoad'. Line 64, position 5.	SigmaReplacementsTextures	D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\Textures\Nyan.resx	64	
Error		Invalid Resx file. Could not find file 'D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\[Nyan]\nyanHead'. Line 64, position 5.	SigmaReplacementsHeads	D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\Heads\Nyan.resx	64	
Error		Invalid Resx file. Could not find file 'D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\[Nyan]\nyanGround'. Line 64, position 5.	SigmaReplacementsMenuScenes	D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\MenuScenes\Nyan.resx	64	
Error		Invalid Resx file. Could not find file 'D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\[Nyan]\nyanBall'. Line 64, position 5.	SigmaReplacementsNavigation	D:\Users\jbb\github\Sigma-Replacements\[Source]\SigmaReplacements\Navigation\Nyan.resx	64

**Comment by Sigma88** [comment]
Ah yes, I usually don't upload images to github to avoid having very big repos.
I'll send you the folder as soon as I get home

What kind of bugs are you working on?

**Comment by Sigma88** [comment]
closing this now since the bugs have been solved, for future reference see:

#83 #84 #86
